name: hello_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_mobile_ads: 3.0.0
  webview_flutter: ^4.2.2
  webview_flutter_android: ^3.10.0
  permission_handler: ^10.4.0    # İzinleri yönetmek için

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/web/index.html
    - assets/web/indexpic.html
    - assets/web/style.css
    - assets/web/script.js
