name: hello_flutter
description: A new Flutter project.
publish_to: 'none'  # Bu paket pub.dev'e yüklenmez
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_mobile_ads: 3.0.0  # 3.1.0 kullanma, namespace hatası var

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

# -- Buraya override ekleyebilirsin --
# dependency_overrides:
#   google_mobile_ads:
#     path: ads_override/google_mobile_ads
